// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJDOG2tpK5CNct7eOPf-1ITe3aUScMps',
    appId: '1:582904473207:web:eaf50d8f5292259ab9c872',
    messagingSenderId: '582904473207',
    projectId: 'systex-99cff',
    authDomain: 'systex-99cff.firebaseapp.com',
    storageBucket: 'systex-99cff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBWWuRImpNJRuyb5pkan_KqmbL8lPOHA',
    appId: '1:582904473207:android:9e1ddc7a191063e1b9c872',
    messagingSenderId: '582904473207',
    projectId: 'systex-99cff',
    storageBucket: 'systex-99cff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtcMqSJuYdAV4xAZrLmbGwHk828HQ16OA',
    appId: '1:582904473207:ios:0eca8224910cab54b9c872',
    messagingSenderId: '582904473207',
    projectId: 'systex-99cff',
    storageBucket: 'systex-99cff.appspot.com',
    iosClientId: '582904473207-jb3kmblej3v6v13dlorjpv3jbq82a9rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.systex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtcMqSJuYdAV4xAZrLmbGwHk828HQ16OA',
    appId: '1:582904473207:ios:0eca8224910cab54b9c872',
    messagingSenderId: '582904473207',
    projectId: 'systex-99cff',
    storageBucket: 'systex-99cff.appspot.com',
    iosClientId: '582904473207-jb3kmblej3v6v13dlorjpv3jbq82a9rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.systex',
  );
}
